// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "large_message.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* LargeMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LargeMessage_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_large_5fmessage_2eproto() {
  protobuf_AddDesc_large_5fmessage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "large_message.proto");
  GOOGLE_CHECK(file != NULL);
  LargeMessage_descriptor_ = file->message_type(0);
  static const int LargeMessage_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LargeMessage, baz_),
  };
  LargeMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      LargeMessage_descriptor_,
      LargeMessage::default_instance_,
      LargeMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LargeMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LargeMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(LargeMessage));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_large_5fmessage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    LargeMessage_descriptor_, &LargeMessage::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_large_5fmessage_2eproto() {
  delete LargeMessage::default_instance_;
  delete LargeMessage_reflection_;
}

void protobuf_AddDesc_large_5fmessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023large_message.proto\"\033\n\014LargeMessage\022\013\n"
    "\003baz\030\001 \002(\014", 50);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "large_message.proto", &protobuf_RegisterTypes);
  LargeMessage::default_instance_ = new LargeMessage();
  LargeMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_large_5fmessage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_large_5fmessage_2eproto {
  StaticDescriptorInitializer_large_5fmessage_2eproto() {
    protobuf_AddDesc_large_5fmessage_2eproto();
  }
} static_descriptor_initializer_large_5fmessage_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int LargeMessage::kBazFieldNumber;
#endif  // !_MSC_VER

LargeMessage::LargeMessage()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void LargeMessage::InitAsDefaultInstance() {
}

LargeMessage::LargeMessage(const LargeMessage& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void LargeMessage::SharedCtor() {
  _cached_size_ = 0;
  baz_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

LargeMessage::~LargeMessage() {
  SharedDtor();
}

void LargeMessage::SharedDtor() {
  if (baz_ != &::google::protobuf::internal::kEmptyString) {
    delete baz_;
  }
  if (this != default_instance_) {
  }
}

void LargeMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LargeMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LargeMessage_descriptor_;
}

const LargeMessage& LargeMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_large_5fmessage_2eproto();  return *default_instance_;
}

LargeMessage* LargeMessage::default_instance_ = NULL;

LargeMessage* LargeMessage::New() const {
  return new LargeMessage;
}

void LargeMessage::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_baz()) {
      if (baz_ != &::google::protobuf::internal::kEmptyString) {
        baz_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool LargeMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bytes baz = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_baz()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void LargeMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required bytes baz = 1;
  if (has_baz()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      1, this->baz(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* LargeMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required bytes baz = 1;
  if (has_baz()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->baz(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int LargeMessage::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bytes baz = 1;
    if (has_baz()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->baz());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LargeMessage::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const LargeMessage* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const LargeMessage*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void LargeMessage::MergeFrom(const LargeMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_baz()) {
      set_baz(from.baz());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void LargeMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LargeMessage::CopyFrom(const LargeMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LargeMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  return true;
}

void LargeMessage::Swap(LargeMessage* other) {
  if (other != this) {
    std::swap(baz_, other->baz_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata LargeMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = LargeMessage_descriptor_;
  metadata.reflection = LargeMessage_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
