// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: large_message.proto

#ifndef PROTOBUF_large_5fmessage_2eproto__INCLUDED
#define PROTOBUF_large_5fmessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_large_5fmessage_2eproto();
void protobuf_AssignDesc_large_5fmessage_2eproto();
void protobuf_ShutdownFile_large_5fmessage_2eproto();

class LargeMessage;

// ===================================================================

class LargeMessage : public ::google::protobuf::Message {
 public:
  LargeMessage();
  virtual ~LargeMessage();
  
  LargeMessage(const LargeMessage& from);
  
  inline LargeMessage& operator=(const LargeMessage& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const LargeMessage& default_instance();
  
  void Swap(LargeMessage* other);
  
  // implements Message ----------------------------------------------
  
  LargeMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LargeMessage& from);
  void MergeFrom(const LargeMessage& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required bytes baz = 1;
  inline bool has_baz() const;
  inline void clear_baz();
  static const int kBazFieldNumber = 1;
  inline const ::std::string& baz() const;
  inline void set_baz(const ::std::string& value);
  inline void set_baz(const char* value);
  inline void set_baz(const void* value, size_t size);
  inline ::std::string* mutable_baz();
  inline ::std::string* release_baz();
  
  // @@protoc_insertion_point(class_scope:LargeMessage)
 private:
  inline void set_has_baz();
  inline void clear_has_baz();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* baz_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_large_5fmessage_2eproto();
  friend void protobuf_AssignDesc_large_5fmessage_2eproto();
  friend void protobuf_ShutdownFile_large_5fmessage_2eproto();
  
  void InitAsDefaultInstance();
  static LargeMessage* default_instance_;
};
// ===================================================================


// ===================================================================

// LargeMessage

// required bytes baz = 1;
inline bool LargeMessage::has_baz() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LargeMessage::set_has_baz() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LargeMessage::clear_has_baz() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LargeMessage::clear_baz() {
  if (baz_ != &::google::protobuf::internal::kEmptyString) {
    baz_->clear();
  }
  clear_has_baz();
}
inline const ::std::string& LargeMessage::baz() const {
  return *baz_;
}
inline void LargeMessage::set_baz(const ::std::string& value) {
  set_has_baz();
  if (baz_ == &::google::protobuf::internal::kEmptyString) {
    baz_ = new ::std::string;
  }
  baz_->assign(value);
}
inline void LargeMessage::set_baz(const char* value) {
  set_has_baz();
  if (baz_ == &::google::protobuf::internal::kEmptyString) {
    baz_ = new ::std::string;
  }
  baz_->assign(value);
}
inline void LargeMessage::set_baz(const void* value, size_t size) {
  set_has_baz();
  if (baz_ == &::google::protobuf::internal::kEmptyString) {
    baz_ = new ::std::string;
  }
  baz_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* LargeMessage::mutable_baz() {
  set_has_baz();
  if (baz_ == &::google::protobuf::internal::kEmptyString) {
    baz_ = new ::std::string;
  }
  return baz_;
}
inline ::std::string* LargeMessage::release_baz() {
  clear_has_baz();
  if (baz_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = baz_;
    baz_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_large_5fmessage_2eproto__INCLUDED
