// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: small_message.proto

#ifndef PROTOBUF_small_5fmessage_2eproto__INCLUDED
#define PROTOBUF_small_5fmessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_small_5fmessage_2eproto();
void protobuf_AssignDesc_small_5fmessage_2eproto();
void protobuf_ShutdownFile_small_5fmessage_2eproto();

class SmallMessage;

// ===================================================================

class SmallMessage : public ::google::protobuf::Message {
 public:
  SmallMessage();
  virtual ~SmallMessage();
  
  SmallMessage(const SmallMessage& from);
  
  inline SmallMessage& operator=(const SmallMessage& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SmallMessage& default_instance();
  
  void Swap(SmallMessage* other);
  
  // implements Message ----------------------------------------------
  
  SmallMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SmallMessage& from);
  void MergeFrom(const SmallMessage& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 foo = 1;
  inline bool has_foo() const;
  inline void clear_foo();
  static const int kFooFieldNumber = 1;
  inline ::google::protobuf::int32 foo() const;
  inline void set_foo(::google::protobuf::int32 value);
  
  // required bool bar = 2;
  inline bool has_bar() const;
  inline void clear_bar();
  static const int kBarFieldNumber = 2;
  inline bool bar() const;
  inline void set_bar(bool value);
  
  // @@protoc_insertion_point(class_scope:SmallMessage)
 private:
  inline void set_has_foo();
  inline void clear_has_foo();
  inline void set_has_bar();
  inline void clear_has_bar();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 foo_;
  bool bar_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_small_5fmessage_2eproto();
  friend void protobuf_AssignDesc_small_5fmessage_2eproto();
  friend void protobuf_ShutdownFile_small_5fmessage_2eproto();
  
  void InitAsDefaultInstance();
  static SmallMessage* default_instance_;
};
// ===================================================================


// ===================================================================

// SmallMessage

// required int32 foo = 1;
inline bool SmallMessage::has_foo() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SmallMessage::set_has_foo() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SmallMessage::clear_has_foo() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SmallMessage::clear_foo() {
  foo_ = 0;
  clear_has_foo();
}
inline ::google::protobuf::int32 SmallMessage::foo() const {
  return foo_;
}
inline void SmallMessage::set_foo(::google::protobuf::int32 value) {
  set_has_foo();
  foo_ = value;
}

// required bool bar = 2;
inline bool SmallMessage::has_bar() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SmallMessage::set_has_bar() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SmallMessage::clear_has_bar() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SmallMessage::clear_bar() {
  bar_ = false;
  clear_has_bar();
}
inline bool SmallMessage::bar() const {
  return bar_;
}
inline void SmallMessage::set_bar(bool value) {
  set_has_bar();
  bar_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_small_5fmessage_2eproto__INCLUDED
